/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectProjectIdRouteImport } from './routes/project/$projectId'
import { Route as DashboardDashboardRouteImport } from './routes/_dashboard/dashboard'
import { Route as ProjectProjectIdSketchRouteImport } from './routes/project/$projectId/sketch'
import { Route as ProjectProjectIdSchemaRouteImport } from './routes/project/$projectId/schema'
import { Route as ProjectProjectIdProfileRouteImport } from './routes/project/$projectId/profile'
import { Route as ProjectProjectIdHistoryRouteImport } from './routes/project/$projectId/history'
import { Route as ProjectProjectIdDataRouteImport } from './routes/project/$projectId/data'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdRoute = ProjectProjectIdRouteImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRoute,
} as any)
const ProjectProjectIdSketchRoute = ProjectProjectIdSketchRouteImport.update({
  id: '/sketch',
  path: '/sketch',
  getParentRoute: () => ProjectProjectIdRoute,
} as any)
const ProjectProjectIdSchemaRoute = ProjectProjectIdSchemaRouteImport.update({
  id: '/schema',
  path: '/schema',
  getParentRoute: () => ProjectProjectIdRoute,
} as any)
const ProjectProjectIdProfileRoute = ProjectProjectIdProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ProjectProjectIdRoute,
} as any)
const ProjectProjectIdHistoryRoute = ProjectProjectIdHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => ProjectProjectIdRoute,
} as any)
const ProjectProjectIdDataRoute = ProjectProjectIdDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => ProjectProjectIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/project/$projectId': typeof ProjectProjectIdRouteWithChildren
  '/project/$projectId/data': typeof ProjectProjectIdDataRoute
  '/project/$projectId/history': typeof ProjectProjectIdHistoryRoute
  '/project/$projectId/profile': typeof ProjectProjectIdProfileRoute
  '/project/$projectId/schema': typeof ProjectProjectIdSchemaRoute
  '/project/$projectId/sketch': typeof ProjectProjectIdSketchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/project/$projectId': typeof ProjectProjectIdRouteWithChildren
  '/project/$projectId/data': typeof ProjectProjectIdDataRoute
  '/project/$projectId/history': typeof ProjectProjectIdHistoryRoute
  '/project/$projectId/profile': typeof ProjectProjectIdProfileRoute
  '/project/$projectId/schema': typeof ProjectProjectIdSchemaRoute
  '/project/$projectId/sketch': typeof ProjectProjectIdSketchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_dashboard/dashboard': typeof DashboardDashboardRoute
  '/project/$projectId': typeof ProjectProjectIdRouteWithChildren
  '/project/$projectId/data': typeof ProjectProjectIdDataRoute
  '/project/$projectId/history': typeof ProjectProjectIdHistoryRoute
  '/project/$projectId/profile': typeof ProjectProjectIdProfileRoute
  '/project/$projectId/schema': typeof ProjectProjectIdSchemaRoute
  '/project/$projectId/sketch': typeof ProjectProjectIdSketchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/project/$projectId'
    | '/project/$projectId/data'
    | '/project/$projectId/history'
    | '/project/$projectId/profile'
    | '/project/$projectId/schema'
    | '/project/$projectId/sketch'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/project/$projectId'
    | '/project/$projectId/data'
    | '/project/$projectId/history'
    | '/project/$projectId/profile'
    | '/project/$projectId/schema'
    | '/project/$projectId/sketch'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/_dashboard/dashboard'
    | '/project/$projectId'
    | '/project/$projectId/data'
    | '/project/$projectId/history'
    | '/project/$projectId/profile'
    | '/project/$projectId/schema'
    | '/project/$projectId/sketch'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ProjectProjectIdRoute: typeof ProjectProjectIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId': {
      id: '/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof ProjectProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/project/$projectId/sketch': {
      id: '/project/$projectId/sketch'
      path: '/sketch'
      fullPath: '/project/$projectId/sketch'
      preLoaderRoute: typeof ProjectProjectIdSketchRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/schema': {
      id: '/project/$projectId/schema'
      path: '/schema'
      fullPath: '/project/$projectId/schema'
      preLoaderRoute: typeof ProjectProjectIdSchemaRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/profile': {
      id: '/project/$projectId/profile'
      path: '/profile'
      fullPath: '/project/$projectId/profile'
      preLoaderRoute: typeof ProjectProjectIdProfileRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/history': {
      id: '/project/$projectId/history'
      path: '/history'
      fullPath: '/project/$projectId/history'
      preLoaderRoute: typeof ProjectProjectIdHistoryRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/data': {
      id: '/project/$projectId/data'
      path: '/data'
      fullPath: '/project/$projectId/data'
      preLoaderRoute: typeof ProjectProjectIdDataRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardDashboardRoute: typeof DashboardDashboardRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDashboardRoute: DashboardDashboardRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ProjectProjectIdRouteChildren {
  ProjectProjectIdDataRoute: typeof ProjectProjectIdDataRoute
  ProjectProjectIdHistoryRoute: typeof ProjectProjectIdHistoryRoute
  ProjectProjectIdProfileRoute: typeof ProjectProjectIdProfileRoute
  ProjectProjectIdSchemaRoute: typeof ProjectProjectIdSchemaRoute
  ProjectProjectIdSketchRoute: typeof ProjectProjectIdSketchRoute
}

const ProjectProjectIdRouteChildren: ProjectProjectIdRouteChildren = {
  ProjectProjectIdDataRoute: ProjectProjectIdDataRoute,
  ProjectProjectIdHistoryRoute: ProjectProjectIdHistoryRoute,
  ProjectProjectIdProfileRoute: ProjectProjectIdProfileRoute,
  ProjectProjectIdSchemaRoute: ProjectProjectIdSchemaRoute,
  ProjectProjectIdSketchRoute: ProjectProjectIdSketchRoute,
}

const ProjectProjectIdRouteWithChildren =
  ProjectProjectIdRoute._addFileChildren(ProjectProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ProjectProjectIdRoute: ProjectProjectIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
